spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        backend-uri: "https://test-back"
        frontend-uri: "https://test-front"
        registration:
          google:
            callback-path: "/auth/google/callback"
            client-id: secret
            client-secret: secret
          naver:
            client-id: secret
            client-secret: secret
            redirect-uri: http://localhost:8080/auth/naver/callback
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
