spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        backend-uri: "https://test-back"
        frontend-uri: "https://test-front"
        registration:
          google:
            callback-path: "/auth/google/callback"
            client-id: secret
            client-secret: secret
