spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        backend-uri: "https://test-back"
        frontend-uri: "https://test-front"
        registration:
          google:
            client-id: secret
            client-secret: secret
            redirect-uri: "/auth/google/callback"
          naver:
            client-id: secret
            client-secret: secret
            redirect-uri: "/auth/naver/callback"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - profile_image
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "/auth/kakao/callback"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_image
              - profile_nickname
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
