### Toggle bookmark for placeId=1
PUT {{baseUrl}}/api/places/1/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=2
PUT {{baseUrl}}/api/places/2/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=3
PUT {{baseUrl}}/api/places/3/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=4
PUT {{baseUrl}}/api/places/4/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=5
PUT {{baseUrl}}/api/places/5/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=6
PUT {{baseUrl}}/api/places/6/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=7
PUT {{baseUrl}}/api/places/7/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=8
PUT {{baseUrl}}/api/places/8/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=9
PUT {{baseUrl}}/api/places/9/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=10
PUT {{baseUrl}}/api/places/10/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=11
PUT {{baseUrl}}/api/places/11/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=12
PUT {{baseUrl}}/api/places/12/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=13
PUT {{baseUrl}}/api/places/13/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=14
PUT {{baseUrl}}/api/places/14/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}

### Toggle bookmark for placeId=15
PUT {{baseUrl}}/api/places/15/bookmarks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderIds": [
    7
  ]
}
