

### Shop 1 - 현대백화점 무역센터점
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "현대백화점 무역센터점",
  "address": "서울특별시 강남구 테헤란로 517",
  "region1depth": "서울특별시",
  "region2depth": "강남구",
  "region3depth": "삼성동",
  "latitude": "37.5087",
  "longitude": "127.0592",
  "categoryName": "Shop",
  "imageUrls": []
}

### Shop 2 - 스타필드 하남
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "스타필드 하남",
  "address": "경기도 하남시 미사대로 750",
  "region1depth": "경기도",
  "region2depth": "하남시",
  "region3depth": "신장동",
  "latitude": "37.5459",
  "longitude": "127.2230",
  "categoryName": "Shop",
  "imageUrls": []
}

### Shop 3 - 이마트 성수점
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "이마트 성수점",
  "address": "서울특별시 성동구 뚝섬로 379",
  "region1depth": "서울특별시",
  "region2depth": "성동구",
  "region3depth": "성수동2가",
  "latitude": "37.5434",
  "longitude": "127.0560",
  "categoryName": "Shop",
  "imageUrls": []
}

### Shop 4 - 남대문시장
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "남대문시장",
  "address": "서울특별시 중구 남창동",
  "region1depth": "서울특별시",
  "region2depth": "중구",
  "region3depth": "남창동",
  "latitude": "37.5593",
  "longitude": "126.9770",
  "categoryName": "Shop",
  "imageUrls": []
}

### Shop 5 - 신세계백화점 본점
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "신세계백화점 본점",
  "address": "서울특별시 중구 소공로 63",
  "region1depth": "서울특별시",
  "region2depth": "중구",
  "region3depth": "소공동",
  "latitude": "37.5609",
  "longitude": "126.9813",
  "categoryName": "Shop",
  "imageUrls": []
}


### Restaurant 1 - 백리향 강남점
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "백리향 강남점",
  "address": "서울특별시 강남구 테헤란로 152",
  "region1depth": "서울특별시",
  "region2depth": "강남구",
  "region3depth": "역삼동",
  "latitude": "37.4981",
  "longitude": "127.0276",
  "categoryName": "Restaurant",
  "imageUrls": []
}

### Restaurant 2 - 삼청동 수제비
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "삼청동 수제비",
  "address": "서울특별시 종로구 삼청로 102",
  "region1depth": "서울특별시",
  "region2depth": "종로구",
  "region3depth": "삼청동",
  "latitude": "37.5875",
  "longitude": "126.9817",
  "categoryName": "Restaurant",
  "imageUrls": []
}

### Restaurant 3 - 명동교자
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "명동교자",
  "address": "서울특별시 중구 명동10길 29",
  "region1depth": "서울특별시",
  "region2depth": "중구",
  "region3depth": "명동",
  "latitude": "37.5637",
  "longitude": "126.9874",
  "categoryName": "Restaurant",
  "imageUrls": []
}

### Restaurant 4 - 진주회관
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "진주회관",
  "address": "서울특별시 중구 세종대로11길 26",
  "region1depth": "서울특별시",
  "region2depth": "중구",
  "region3depth": "북창동",
  "latitude": "37.5661",
  "longitude": "126.9784",
  "categoryName": "Restaurant",
  "imageUrls": []
}

### Restaurant 5 - 노량진 수산시장
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "노량진 수산시장",
  "address": "서울특별시 동작구 노들로 674",
  "region1depth": "서울특별시",
  "region2depth": "동작구",
  "region3depth": "노량진동",
  "latitude": "37.5131",
  "longitude": "126.9407",
  "categoryName": "Restaurant",
  "imageUrls": []
}


### Entertainment 1 - CGV 용산아이파크몰
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "CGV 용산아이파크몰",
  "address": "서울특별시 용산구 한강대로23길 55",
  "region1depth": "서울특별시",
  "region2depth": "용산구",
  "region3depth": "한강로동",
  "latitude": "37.5299",
  "longitude": "126.9646",
  "categoryName": "Entertainment",
  "imageUrls": []
}

### Entertainment 2 - 롯데월드
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "롯데월드",
  "address": "서울특별시 송파구 올림픽로 240",
  "region1depth": "서울특별시",
  "region2depth": "송파구",
  "region3depth": "잠실동",
  "latitude": "37.5110",
  "longitude": "127.0980",
  "categoryName": "Entertainment",
  "imageUrls": []
}

### Entertainment 3 - 잠실야구장
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "잠실야구장",
  "address": "서울특별시 송파구 올림픽로 25",
  "region1depth": "서울특별시",
  "region2depth": "송파구",
  "region3depth": "잠실동",
  "latitude": "37.5121",
  "longitude": "127.0715",
  "categoryName": "Entertainment",
  "imageUrls": []
}

### Entertainment 4 - 남산서울타워
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "남산서울타워",
  "address": "서울특별시 용산구 남산공원길 105",
  "region1depth": "서울특별시",
  "region2depth": "용산구",
  "region3depth": "용산동2가",
  "latitude": "37.5512",
  "longitude": "126.9882",
  "categoryName": "Entertainment",
  "imageUrls": []
}

### Entertainment 5 - 잠실 롯데콘서트홀
POST {{baseUrl}}/api/places/admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "잠실 롯데콘서트홀",
  "address": "서울특별시 송파구 올림픽로 300",
  "region1depth": "서울특별시",
  "region2depth": "송파구",
  "region3depth": "신천동",
  "latitude": "37.5132",
  "longitude": "127.1002",
  "categoryName": "Entertainment",
  "imageUrls": []
}
